#Artificial Intelligence
Any technique which enables computers to mimic human behavior.
#Machine Learning
Subset of AI techniques which use statistical methods to enable machines to improve with experiences.
#Deep Learning
Subset of ML which make the computation of multilayer networks feasible.
#Data Science
Data science is a multi-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from structured and unstructured data.

#Data Preprocessing
Preprocessing refers to the transformation applied to our data before feeding it to ML algorithm.
Data Preprocessing is a technique that is used to convert the raw data into a clean data set.

#Numpy
Manipulating numerical data, similar to MATLAB. multi-dimensional arrays and matrices, along with a large collection of high level mathematical function to operate on these arrays.

#Pandas
For Data manipulation, cleaning and analysis,

#Matplotlib
For plotting data, or visualizing the analysis.

#Data Proprocessing

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Datasets (1)/titanic.csv")
df

page_id                                 name  \
0         1678            Spider-Man (Peter Parker)   
1         7139      Captain America (Steven Rogers)   
2        64786  Wolverine (James \"Logan\" Howlett)   
3         1868    Iron Man (Anthony \"Tony\" Stark)   
4         2460                  Thor (Thor Odinson)   
...        ...                                  ...   
16371   657508                   Ru'ach (Earth-616)   
16372   665474      Thane (Thanos' son) (Earth-616)   
16373   695217        Tinkerer (Skrull) (Earth-616)   
16374   708811       TK421 (Spiderling) (Earth-616)   
16375   673702                Yologarch (Earth-616)   

                                       urlslug                ID  \
0                  \/Spider-Man_(Peter_Parker)   Secret Identity   
1            \/Captain_America_(Steven_Rogers)   Public Identity   
2      \/Wolverine_(James_%22Logan%22_Howlett)   Public Identity   
3        \/Iron_Man_(Anthony_%22Tony%22_Stark)   Public Identity   
4                        \/Thor_(Thor_Odinson)  No Dual Identity   
...                                        ...               ...   
16371                   \/Ru%27ach_(Earth-616)  No Dual Identity   
16372      \/Thane_(Thanos%27_son)_(Earth-616)  No Dual Identity   
16373          \/Tinkerer_(Skrull)_(Earth-616)   Secret Identity   
16374         \/TK421_(Spiderling)_(Earth-616)   Secret Identity   
16375                  \/Yologarch_(Earth-616)               NaN   

                    ALIGN         EYE        HAIR              SEX  GSM  \
0         Good Characters  Hazel Eyes  Brown Hair  Male Characters  NaN   
1         Good Characters   Blue Eyes  White Hair  Male Characters  NaN   
2      Neutral Characters   Blue Eyes  Black Hair  Male Characters  NaN   
3         Good Characters   Blue Eyes  Black Hair  Male Characters  NaN   
4         Good Characters   Blue Eyes  Blond Hair  Male Characters  NaN   
...                   ...         ...         ...              ...  ...   
16371      Bad Characters  Green Eyes     No Hair  Male Characters  NaN   
16372     Good Characters   Blue Eyes        Bald  Male Characters  NaN   
16373      Bad Characters  Black Eyes        Bald  Male Characters  NaN   
16374  Neutral Characters         NaN         NaN  Male Characters  NaN   
16375      Bad Characters         NaN         NaN              NaN  NaN   

                   ALIVE  APPEARANCES FIRST APPEARANCE    Year  
0      Living Characters       4043.0           Aug-62  1962.0  
1      Living Characters       3360.0           Mar-41  1941.0  
2      Living Characters       3061.0           Oct-74  1974.0  
3      Living Characters       2961.0           Mar-63  1963.0  
4      Living Characters       2258.0           Nov-50  1950.0  
...                  ...          ...              ...     ...  
16371  Living Characters          NaN              NaN     NaN  
16372  Living Characters          NaN              NaN     NaN  
16373  Living Characters          NaN              NaN     NaN  
16374  Living Characters          NaN              NaN     NaN  
16375  Living Characters          NaN              NaN     NaN  

[16376 rows x 13 columns]

In [75]:
from sklearn.impute import SimpleImputer

In [76]:
sample = df[df['GSM'].notna()]
sample=sample.iloc[-7:-1,[-3,-1]]
sample

APPEARANCES    Year
14106          1.0  2002.0
14163          1.0  2003.0
15528          NaN  1980.0
16041          NaN  2007.0
16144          NaN  2012.0
16363          NaN     NaN

In [77]:
imputer1 = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer = imputer1.fit(sample)
sample1 = imputer.transform(sample)
sample1

array([[1.0000e+00, 2.0020e+03],
       [1.0000e+00, 2.0030e+03],
       [1.0000e+00, 1.9800e+03],
       [1.0000e+00, 2.0070e+03],
       [1.0000e+00, 2.0120e+03],
       [1.0000e+00, 2.0008e+03]])

In [78]:
sample = df[df['GSM'].notna()]
sample=sample.iloc[-10:-1,[-3,-1]]
sample

APPEARANCES    Year
10066          2.0  2005.0
13695          1.0  1997.0
13985          1.0  2001.0
14106          1.0  2002.0
14163          1.0  2003.0
15528          NaN  1980.0
16041          NaN  2007.0
16144          NaN  2012.0
16363          NaN     NaN

In [79]:
imputer2 = SimpleImputer(missing_values=np.nan,strategy="median")
imputer = imputer2.fit(sample)
sample2 = imputer.transform(sample)
sample2

array([[2.0000e+00, 2.0050e+03],
       [1.0000e+00, 1.9970e+03],
       [1.0000e+00, 2.0010e+03],
       [1.0000e+00, 2.0020e+03],
       [1.0000e+00, 2.0030e+03],
       [1.0000e+00, 1.9800e+03],
       [1.0000e+00, 2.0070e+03],
       [1.0000e+00, 2.0120e+03],
       [1.0000e+00, 2.0025e+03]])

In [80]:
sample = df[df['GSM'].notna()]
sample=sample.iloc[-15:-10,[-3,-1]]
sample

APPEARANCES    Year
7945          3.0  2001.0
8386          3.0     NaN
9554          2.0  1994.0
9799          2.0  1998.0
9973          2.0  2003.0

In [81]:
imputer3 = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
imputer = imputer3.fit(sample)
sample3 = imputer.transform(sample)
sample3

array([[3.000e+00, 2.001e+03],
       [3.000e+00, 1.994e+03],
       [2.000e+00, 1.994e+03],
       [2.000e+00, 1.998e+03],
       [2.000e+00, 2.003e+03]])

In [85]:
df2 = pd.read_csv("/content/drive/MyDrive/Datasets (1)/2013-2017_School_Math_Results_-_Gender (1).csv")

In [92]:
df2.head()

Gender  Height  Weight    BMI  Category
0    Male     NaN    96.0    NaN       NaN
1    Male   189.0    87.0  24.36       1.0
2  Female   185.0   110.0  32.14       3.0
3  Female   195.0   104.0  27.35       2.0
4    Male   149.0    61.0  27.48       2.0

In [96]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
df2.iloc[:,0]=LE.fit_transform(df2.iloc[:,0])

In [97]:
df2.head()

Gender  Height  Weight    BMI  Category
0       1     NaN    96.0    NaN       NaN
1       1   189.0    87.0  24.36       1.0
2       0   185.0   110.0  32.14       3.0
3       0   195.0   104.0  27.35       2.0
4       1   149.0    61.0  27.48       2.0

In [101]:
df2.iloc[:,[1,4]]=imputer2.fit_transform(df2.iloc[:,[1,4]])

In [102]:
df2.head()

Gender  Height  Weight    BMI  Category
0       1   170.0    96.0  36.95       3.0
1       1   189.0    87.0  24.36       1.0
2       0   185.0   110.0  32.14       3.0
3       0   195.0   104.0  27.35       2.0
4       1   149.0    61.0  27.48       2.0

In [120]:
from sklearn.preprocessing import OneHotEncoder

In [199]:
OHE = OneHotEncoder()

In [236]:
df3 = pd.read_csv("/content/drive/MyDrive/Datasets (1)/2013-2017_School_Math_Results_-_Gender (1).csv")

In [237]:
df3.head()

Gender  Height  Weight    BMI  Category
0    Male     NaN    96.0    NaN       NaN
1    Male   189.0    87.0  24.36       1.0
2  Female   185.0   110.0  32.14       3.0
3  Female   195.0   104.0  27.35       2.0
4    Male   149.0    61.0  27.48       2.0

In [238]:
imputer2=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
df3.iloc[:,4]=imputer2.fit_transform(pd.DataFrame(df3.iloc[:,4]))
imputer3=SimpleImputer(missing_values=np.nan,strategy="median")
df3.iloc[:,1:4]=imputer3.fit_transform(df3.iloc[:,1:4])

In [239]:
df3

Gender  Height  Weight    BMI  Category
0      Male   170.0    96.0  36.95       3.0
1      Male   189.0    87.0  24.36       1.0
2    Female   185.0   110.0  32.14       3.0
3    Female   195.0   104.0  27.35       2.0
4      Male   149.0    61.0  27.48       2.0
..      ...     ...     ...    ...       ...
495  Female   150.0   153.0  68.00       3.0
496  Female   184.0   121.0  35.74       3.0
497  Female   141.0   136.0  68.41       3.0
498    Male   150.0    95.0  42.22       3.0
499    Male   173.0   131.0  43.77       3.0

[500 rows x 5 columns]

In [240]:
dff=pd.DataFrame(OHE.fit_transform(df3[['Gender']]).toarray())
df3 = df3.join(dff)
df3=df3.iloc[:,1:]
df3

Height  Weight    BMI  Category    0    1
0     170.0    96.0  36.95       3.0  0.0  1.0
1     189.0    87.0  24.36       1.0  0.0  1.0
2     185.0   110.0  32.14       3.0  1.0  0.0
3     195.0   104.0  27.35       2.0  1.0  0.0
4     149.0    61.0  27.48       2.0  0.0  1.0
..      ...     ...    ...       ...  ...  ...
495   150.0   153.0  68.00       3.0  1.0  0.0
496   184.0   121.0  35.74       3.0  1.0  0.0
497   141.0   136.0  68.41       3.0  1.0  0.0
498   150.0    95.0  42.22       3.0  0.0  1.0
499   173.0   131.0  43.77       3.0  0.0  1.0

[500 rows x 6 columns]

In [241]:
from sklearn.model_selection import train_test_split

In [243]:
x=df3.iloc[:,[0,1,2,4,5]]
y=df3.iloc[:,3]

In [253]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [254]:
from sklearn.preprocessing import StandardScaler

In [255]:
sc = StandardScaler()

In [256]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,


In [257]:
x_train.shape

(350, 5)